//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEntityProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employ
    {
        public int Employ_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string City { get; set; }
    }
}
